if (NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SOURCE_DIR is required")
endif()

file(READ "${SOURCE_DIR}/src/solver/multiway_traversal.cpp" TRAVERSAL_SOURCE)
file(READ "${SOURCE_DIR}/include/solver/multiway_public_builder.hpp" BUILDER_HEADER)

if (TRAVERSAL_SOURCE MATCHES "std::vector<MultiwayActionDescriptor> child_actions")
    message(FATAL_ERROR "multiway traversal still allocates a dynamic child action menu")
endif()
if (NOT TRAVERSAL_SOURCE MATCHES "std::array<MultiwayActionDescriptor")
    message(FATAL_ERROR "multiway traversal lost its bounded action scratch")
endif()
if (NOT BUILDER_HEADER MATCHES "child_action_count")
    message(FATAL_ERROR "public builder lacks a bounded action scratch boundary")
endif()
