if (NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SOURCE_DIR is required")
endif()

file(READ "${SOURCE_DIR}/CMakeLists.txt" project_cmake)
if (NOT project_cmake MATCHES "_texassolver_saved_defined_BUILD_TESTS")
    message(FATAL_ERROR "evaluator option setup does not save parent BUILD_TESTS state")
endif()
if (project_cmake MATCHES "unset\\(BUILD_TESTS\\)")
    message(FATAL_ERROR "evaluator option setup discards the parent BUILD_TESTS state")
endif()
if (NOT project_cmake MATCHES "_texassolver_saved_value_BUILD_CARD7")
    message(FATAL_ERROR "evaluator option setup does not save all evaluator options")
endif()
