if (NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SOURCE_DIR is required")
endif()

file(READ "${SOURCE_DIR}/include/solver/multiway/resolver/multiway_resolver.hpp" RESOLVER_HEADER)
file(READ "${SOURCE_DIR}/src/solver/multiway/resolver/multiway_resolver.cpp" RESOLVER_SOURCE)
file(READ "${SOURCE_DIR}/include/solver/multiway/session/multiway_decision_session.hpp" SESSION_HEADER)

if (RESOLVER_HEADER MATCHES "MultiwayRuntimeSession|begin_runtime_session")
    message(FATAL_ERROR "the retired runtime-session API remains public")
endif()
if (RESOLVER_SOURCE MATCHES "MultiwaySearchSession session")
    message(FATAL_ERROR "release search still owns a parallel raw search session")
endif()
if (NOT RESOLVER_SOURCE MATCHES "MultiwayDecisionSession session")
    message(FATAL_ERROR "release search does not use the decision-session owner")
endif()
if (NOT SESSION_HEADER MATCHES "observe_action" OR NOT SESSION_HEADER MATCHES "reroot")
    message(FATAL_ERROR "decision session does not expose the live-hand lifecycle")
endif()
