#include "solver/multiway/blueprint/multiway_training_checkpoint_artifact.hpp"

#include "core/atomic_publish.hpp"
#include "core/fingerprint.hpp"
#include "core/portable_binary.hpp"

#include <array>
#include <cmath>
#include <cstring>
#include <fstream>
#include <limits>
#include <stdexcept>

namespace texas::solver::multiway {
namespace {
namespace portable = texas::core::portable;

constexpr std::array<char, 8> kMagic = {'M', 'W', 'T', 'C', '0', '0', '0', '1'};
constexpr std::uint32_t kSchema = 1U;
constexpr std::uint64_t kMaxFileBytes = 60ULL * 1024ULL * 1024ULL * 1024ULL;
constexpr std::uint32_t kMaxStates = 100000000U;
constexpr std::uint32_t kMaxRows = 100000000U;

void require(bool ok) { if (!ok) throw std::runtime_error("multiway training checkpoint is truncated"); }
void write_double(std::ostream& out, double value) { std::uint64_t bits; std::memcpy(&bits, &value, sizeof(bits)); portable::write_u64(out, bits); }
bool read_double(std::istream& in, double& value) { std::uint64_t bits = 0U; if (!portable::read_u64(in, bits)) return false; std::memcpy(&value, &bits, sizeof(value)); return true; }
void write_identity(std::ostream& out, const MultiwayModelIdentity& value) { visit_multiway_model_identity_fields(value, [&](std::uint64_t field) { portable::write_u64(out, field); }); }
bool read_identity(std::istream& in, MultiwayModelIdentity& value) { bool ok = true; visit_multiway_model_identity_fields(value, [&](std::uint64_t& field) { if (ok) ok = portable::read_u64(in, field); }); return ok; }
void write_action(std::ostream& out, const MultiwayActionDescriptor& value) { portable::write_u8(out, static_cast<std::uint8_t>(value.action)); portable::write_u32(out, value.action_index); portable::write_i32(out, value.target_street_contribution); portable::write_u64(out, value.action_menu_id); }
bool read_action(std::istream& in, MultiwayActionDescriptor& value) { std::uint8_t action = 0U; if (!portable::read_u8(in, action) || !portable::read_u32(in, value.action_index) || !portable::read_i32(in, value.target_street_contribution) || !portable::read_u64(in, value.action_menu_id)) return false; value.action = static_cast<MultiwayAction>(action); return true; }
void write_ints(std::ostream& out, const std::vector<int>& values) { portable::write_u8(out, static_cast<std::uint8_t>(values.size())); for (const auto value : values) portable::write_i32(out, value); }
bool read_ints(std::istream& in, std::vector<int>& values) { std::uint8_t size = 0U; if (!portable::read_u8(in, size) || size > 6U) return false; values.resize(size); for (auto& value : values) if (!portable::read_i32(in, value)) return false; return true; }
void write_bools(std::ostream& out, const std::vector<bool>& values) { portable::write_u8(out, static_cast<std::uint8_t>(values.size())); for (const auto value : values) portable::write_u8(out, value ? 1U : 0U); }
bool read_bools(std::istream& in, std::vector<bool>& values) { std::uint8_t size = 0U; if (!portable::read_u8(in, size) || size > 6U) return false; values.assign(size, false); for (std::size_t index = 0U; index < size; ++index) { std::uint8_t value = 0U; if (!portable::read_u8(in, value) || value > 1U) return false; values[index] = value != 0U; } return true; }
void write_cards(std::ostream& out, const std::vector<std::uint8_t>& values) { portable::write_u8(out, static_cast<std::uint8_t>(values.size())); for (const auto value : values) portable::write_u8(out, value); }
bool read_cards(std::istream& in, std::vector<std::uint8_t>& values, std::uint8_t maximum = 5U) { std::uint8_t size = 0U; if (!portable::read_u8(in, size) || size > maximum) return false; values.resize(size); for (auto& value : values) if (!portable::read_u8(in, value)) return false; return true; }
void write_betting(std::ostream& out, const MultiwayBettingSnapshot& value) { write_ints(out, value.stacks); write_ints(out, value.contributions); write_ints(out, value.street_contributions); write_bools(out, value.folded); write_bools(out, value.all_in); write_bools(out, value.may_raise); write_bools(out, value.pending); write_bools(out, value.has_acted); write_ints(out, value.bet_faced_when_acted); portable::write_i32(out, value.current_player); portable::write_i32(out, value.last_aggressor); portable::write_i32(out, value.current_bet); portable::write_i32(out, value.last_full_raise_size); portable::write_i32(out, value.big_blind); portable::write_u8(out, static_cast<std::uint8_t>(value.street)); }
bool read_betting(std::istream& in, MultiwayBettingSnapshot& value) { std::uint8_t street = 0U; return read_ints(in, value.stacks) && read_ints(in, value.contributions) && read_ints(in, value.street_contributions) && read_bools(in, value.folded) && read_bools(in, value.all_in) && read_bools(in, value.may_raise) && read_bools(in, value.pending) && read_bools(in, value.has_acted) && read_ints(in, value.bet_faced_when_acted) && portable::read_i32(in, value.current_player) && portable::read_i32(in, value.last_aggressor) && portable::read_i32(in, value.current_bet) && portable::read_i32(in, value.last_full_raise_size) && portable::read_i32(in, value.big_blind) && portable::read_u8(in, street) && ((value.street = static_cast<Street>(street)), true); }
void write_state(std::ostream& out, const MultiwayPublicStateDescriptor& value) { portable::write_u64(out, value.id.value); portable::write_u64(out, value.parent_id.value); portable::write_u8(out, static_cast<std::uint8_t>(value.incoming_edge.kind)); write_action(out, value.incoming_edge.action); portable::write_u8(out, value.incoming_edge.dealt_card); write_cards(out, value.incoming_edge.dealt_cards); write_cards(out, value.incoming_edge.transition_board); portable::write_u64(out, value.canonical_history_id); write_betting(out, value.betting); write_cards(out, value.board); portable::write_u8(out, value.board_runout.remaining_board_cards); portable::write_u8(out, value.board_runout.chance_only_runout ? 1U : 0U); portable::write_u32(out, static_cast<std::uint32_t>(value.history.size())); for (const auto& entry : value.history) { portable::write_i32(out, entry.actor); write_action(out, entry.action); } portable::write_u8(out, static_cast<std::uint8_t>(value.legal_actions.size())); for (const auto& action : value.legal_actions) write_action(out, action); }
bool read_state(std::istream& in, MultiwayPublicStateDescriptor& value) { std::uint8_t kind = 0U, chance_only = 0U, actions = 0U; std::uint32_t history = 0U; if (!portable::read_u64(in, value.id.value) || !portable::read_u64(in, value.parent_id.value) || !portable::read_u8(in, kind) || !read_action(in, value.incoming_edge.action) || !portable::read_u8(in, value.incoming_edge.dealt_card) || !read_cards(in, value.incoming_edge.dealt_cards) || !read_cards(in, value.incoming_edge.transition_board) || !portable::read_u64(in, value.canonical_history_id) || !read_betting(in, value.betting) || !read_cards(in, value.board) || !portable::read_u8(in, value.board_runout.remaining_board_cards) || !portable::read_u8(in, chance_only) || chance_only > 1U || !portable::read_u32(in, history) || history > 512U) return false; value.incoming_edge.kind = static_cast<MultiwayPublicParentEdgeKind>(kind); value.board_runout.chance_only_runout = chance_only != 0U; value.history.resize(history); for (auto& entry : value.history) if (!portable::read_i32(in, entry.actor) || !read_action(in, entry.action)) return false; if (!portable::read_u8(in, actions) || actions > 6U) return false; value.legal_actions.resize(actions); for (auto& action : value.legal_actions) if (!read_action(in, action)) return false; return true; }
void write_metadata(std::ostream& out, const MultiwayBlueprintTrainingMetadata& value) { portable::write_u64(out, value.batches); portable::write_u64(out, value.trajectories); portable::write_u64(out, value.deterministic_seed); portable::write_u64(out, value.late_window_start_batch); portable::write_u64(out, value.schedule_hash); portable::write_u64(out, value.pruned_negative_regrets); portable::write_u64(out, value.terminal_visits); portable::write_u64(out, value.leaf_visits); portable::write_u64(out, value.missing_lookup_requests); portable::write_u8(out, value.linear_iteration_weighting); portable::write_u8(out, value.discounting_enabled); portable::write_u8(out, value.negative_regret_pruning_enabled); portable::write_u8(out, value.reserved); }
bool read_metadata(std::istream& in, MultiwayBlueprintTrainingMetadata& value) { return portable::read_u64(in, value.batches) && portable::read_u64(in, value.trajectories) && portable::read_u64(in, value.deterministic_seed) && portable::read_u64(in, value.late_window_start_batch) && portable::read_u64(in, value.schedule_hash) && portable::read_u64(in, value.pruned_negative_regrets) && portable::read_u64(in, value.terminal_visits) && portable::read_u64(in, value.leaf_visits) && portable::read_u64(in, value.missing_lookup_requests) && portable::read_u8(in, value.linear_iteration_weighting) && portable::read_u8(in, value.discounting_enabled) && portable::read_u8(in, value.negative_regret_pruning_enabled) && portable::read_u8(in, value.reserved); }
void append(std::uint64_t& hash, std::uint64_t value) noexcept { core::fingerprint::append_u64(hash, value); }
void append_double(std::uint64_t& hash, double value) noexcept { std::uint64_t bits = 0U; std::memcpy(&bits, &value, sizeof(bits)); append(hash, bits); }
void hash_ints(std::uint64_t& hash, const std::vector<int>& values) noexcept { append(hash, values.size()); for (const auto value : values) append(hash, static_cast<std::uint64_t>(static_cast<std::int64_t>(value))); }
void hash_bools(std::uint64_t& hash, const std::vector<bool>& values) noexcept { append(hash, values.size()); for (const auto value : values) append(hash, value ? 1U : 0U); }
void hash_cards(std::uint64_t& hash, const std::vector<std::uint8_t>& values) noexcept { append(hash, values.size()); for (const auto value : values) append(hash, value); }
void hash_action(std::uint64_t& hash, const MultiwayActionDescriptor& value) noexcept { append(hash, static_cast<std::uint8_t>(value.action)); append(hash, value.action_index); append(hash, static_cast<std::uint64_t>(static_cast<std::int64_t>(value.target_street_contribution))); append(hash, value.action_menu_id); }
void hash_state(std::uint64_t& hash, const MultiwayPublicStateDescriptor& state) noexcept { append(hash, state.id.value); append(hash, state.parent_id.value); append(hash, static_cast<std::uint8_t>(state.incoming_edge.kind)); hash_action(hash, state.incoming_edge.action); append(hash, state.incoming_edge.dealt_card); hash_cards(hash, state.incoming_edge.dealt_cards); hash_cards(hash, state.incoming_edge.transition_board); append(hash, state.canonical_history_id); const auto& betting = state.betting; hash_ints(hash, betting.stacks); hash_ints(hash, betting.contributions); hash_ints(hash, betting.street_contributions); hash_bools(hash, betting.folded); hash_bools(hash, betting.all_in); hash_bools(hash, betting.may_raise); hash_bools(hash, betting.pending); hash_bools(hash, betting.has_acted); hash_ints(hash, betting.bet_faced_when_acted); append(hash, static_cast<std::uint64_t>(static_cast<std::int64_t>(betting.current_player))); append(hash, static_cast<std::uint64_t>(static_cast<std::int64_t>(betting.last_aggressor))); append(hash, static_cast<std::uint64_t>(static_cast<std::int64_t>(betting.current_bet))); append(hash, static_cast<std::uint64_t>(static_cast<std::int64_t>(betting.last_full_raise_size))); append(hash, static_cast<std::uint64_t>(static_cast<std::int64_t>(betting.big_blind))); append(hash, static_cast<std::uint8_t>(betting.street)); hash_cards(hash, state.board); append(hash, state.board_runout.remaining_board_cards); append(hash, state.board_runout.chance_only_runout ? 1U : 0U); append(hash, state.history.size()); for (const auto& entry : state.history) { append(hash, static_cast<std::uint64_t>(static_cast<std::int64_t>(entry.actor))); hash_action(hash, entry.action); } append(hash, state.legal_actions.size()); for (const auto& action : state.legal_actions) hash_action(hash, action); }
}

std::uint64_t MultiwayTrainingCheckpointArtifacts::payload_hash(const MultiwayBlueprintTrainingCheckpoint& checkpoint) noexcept {
    auto hash = core::fingerprint::FNV1A_OFFSET;
    visit_multiway_model_identity_fields(checkpoint.identity, [&](std::uint64_t value) { append(hash, value); });
    const auto& training = checkpoint.training;
    append(hash, training.batches); append(hash, training.trajectories); append(hash, training.deterministic_seed); append(hash, training.late_window_start_batch); append(hash, training.schedule_hash); append(hash, training.pruned_negative_regrets); append(hash, training.terminal_visits); append(hash, training.leaf_visits); append(hash, training.missing_lookup_requests); append(hash, training.linear_iteration_weighting); append(hash, training.discounting_enabled); append(hash, training.negative_regret_pruning_enabled);
    const auto& coverage = checkpoint.coverage;
    append(hash, coverage.visited_public_descriptors); append(hash, coverage.admitted_rows); append(hash, coverage.admitted_action_cells); append(hash, coverage.terminal_visits); append(hash, coverage.leaf_visits); append(hash, coverage.missing_lookup_requests); append(hash, coverage.preflop_rows); append(hash, coverage.flop_rows); append(hash, coverage.turn_rows); append(hash, coverage.river_rows);
    append(hash, checkpoint.coordinator.terminal_visits); append(hash, checkpoint.coordinator.leaf_visits); append(hash, checkpoint.coordinator.missing_lookup_requests); append(hash, checkpoint.coordinator.last_merged_stream_fingerprint);
    append(hash, checkpoint.coordinator.public_states.size()); for (const auto& state : checkpoint.coordinator.public_states) hash_state(hash, state);
    append(hash, checkpoint.coordinator.storage.shapes.size()); for (const auto& shape : checkpoint.coordinator.storage.shapes) { append(hash, shape.infoset.public_state.value); append(hash, static_cast<std::uint64_t>(static_cast<std::int64_t>(shape.infoset.seat))); append(hash, shape.bucket_count); append(hash, shape.action_count); }
    append(hash, checkpoint.coordinator.storage.regrets.size()); for (const auto value : checkpoint.coordinator.storage.regrets) append_double(hash, value); append(hash, checkpoint.coordinator.storage.strategy_sums.size()); for (const auto value : checkpoint.coordinator.storage.strategy_sums) append_double(hash, value); append(hash, checkpoint.late_window_baseline.size()); for (const auto value : checkpoint.late_window_baseline) append_double(hash, value);
    return core::fingerprint::finish(hash);
}

void MultiwayTrainingCheckpointArtifacts::save_atomic(const std::filesystem::path& path, const MultiwayBlueprintTrainingCheckpoint& checkpoint) {
    checkpoint.validate();
    const auto temporary = path.string() + ".tmp";
    std::ofstream out(temporary, std::ios::binary | std::ios::trunc);
    if (!out) throw std::runtime_error("multiway training checkpoint temporary file cannot be opened");
    out.write(kMagic.data(), static_cast<std::streamsize>(kMagic.size())); portable::write_u32(out, kSchema); write_identity(out, checkpoint.identity); write_metadata(out, checkpoint.training);
    const auto& coverage = checkpoint.coverage; portable::write_u64(out, coverage.visited_public_descriptors); portable::write_u64(out, coverage.admitted_rows); portable::write_u64(out, coverage.admitted_action_cells); portable::write_u64(out, coverage.terminal_visits); portable::write_u64(out, coverage.leaf_visits); portable::write_u64(out, coverage.missing_lookup_requests); portable::write_u64(out, coverage.preflop_rows); portable::write_u64(out, coverage.flop_rows); portable::write_u64(out, coverage.turn_rows); portable::write_u64(out, coverage.river_rows); portable::write_u64(out, checkpoint.coordinator.terminal_visits); portable::write_u64(out, checkpoint.coordinator.leaf_visits); portable::write_u64(out, checkpoint.coordinator.missing_lookup_requests); portable::write_u64(out, checkpoint.coordinator.last_merged_stream_fingerprint);
    portable::write_u32(out, static_cast<std::uint32_t>(checkpoint.coordinator.public_states.size())); for (const auto& state : checkpoint.coordinator.public_states) write_state(out, state);
    portable::write_u32(out, static_cast<std::uint32_t>(checkpoint.coordinator.storage.shapes.size())); for (const auto& shape : checkpoint.coordinator.storage.shapes) { portable::write_u64(out, shape.infoset.public_state.value); portable::write_i32(out, shape.infoset.seat); portable::write_u32(out, shape.bucket_count); portable::write_u8(out, shape.action_count); }
    portable::write_u64(out, checkpoint.coordinator.storage.regrets.size()); for (const auto value : checkpoint.coordinator.storage.regrets) write_double(out, value); portable::write_u64(out, checkpoint.coordinator.storage.strategy_sums.size()); for (const auto value : checkpoint.coordinator.storage.strategy_sums) write_double(out, value); portable::write_u64(out, checkpoint.late_window_baseline.size()); for (const auto value : checkpoint.late_window_baseline) write_double(out, value); portable::write_u64(out, payload_hash(checkpoint));
    out.close(); if (!out) throw std::runtime_error("multiway training checkpoint write failed"); core::publish_atomic_replace(temporary, path, "multiway training checkpoint publish failed");
}

MultiwayBlueprintTrainingCheckpoint MultiwayTrainingCheckpointArtifacts::load_verified(const std::filesystem::path& path, const MultiwayModelIdentity& expected_identity, std::uint64_t expected_schedule_hash, std::uint64_t expected_seed) {
    std::error_code error; const auto bytes = std::filesystem::file_size(path, error); if (error || bytes > kMaxFileBytes) throw std::length_error("multiway training checkpoint size is invalid");
    std::ifstream in(path, std::ios::binary); if (!in) throw std::runtime_error("multiway training checkpoint cannot be opened"); std::array<char, kMagic.size()> magic{}; in.read(magic.data(), static_cast<std::streamsize>(magic.size())); std::uint32_t schema = 0U; if (!in || magic != kMagic || !portable::read_u32(in, schema) || schema != kSchema) throw std::runtime_error("multiway training checkpoint schema is invalid");
    MultiwayBlueprintTrainingCheckpoint result; require(read_identity(in, result.identity)); require(read_metadata(in, result.training)); auto& coverage = result.coverage; require(portable::read_u64(in, coverage.visited_public_descriptors) && portable::read_u64(in, coverage.admitted_rows) && portable::read_u64(in, coverage.admitted_action_cells) && portable::read_u64(in, coverage.terminal_visits) && portable::read_u64(in, coverage.leaf_visits) && portable::read_u64(in, coverage.missing_lookup_requests) && portable::read_u64(in, coverage.preflop_rows) && portable::read_u64(in, coverage.flop_rows) && portable::read_u64(in, coverage.turn_rows) && portable::read_u64(in, coverage.river_rows) && portable::read_u64(in, result.coordinator.terminal_visits) && portable::read_u64(in, result.coordinator.leaf_visits) && portable::read_u64(in, result.coordinator.missing_lookup_requests) && portable::read_u64(in, result.coordinator.last_merged_stream_fingerprint));
    std::uint32_t states = 0U; require(portable::read_u32(in, states) && states <= kMaxStates); result.coordinator.public_states.resize(states); for (auto& state : result.coordinator.public_states) require(read_state(in, state)); std::uint32_t shapes = 0U; require(portable::read_u32(in, shapes) && shapes <= kMaxRows); result.coordinator.storage.shapes.resize(shapes); std::size_t expected_values = 0U; for (auto& shape : result.coordinator.storage.shapes) { require(portable::read_u64(in, shape.infoset.public_state.value) && portable::read_i32(in, shape.infoset.seat) && portable::read_u32(in, shape.bucket_count) && portable::read_u8(in, shape.action_count)); const auto count = static_cast<std::size_t>(shape.bucket_count) * shape.action_count; if (shape.bucket_count == 0U || shape.action_count == 0U || count > std::numeric_limits<std::size_t>::max() - expected_values) throw std::length_error("multiway training checkpoint row shapes are invalid"); expected_values += count; } std::uint64_t values = 0U; const auto expected_u64 = static_cast<std::uint64_t>(expected_values); const auto maximum_values = kMaxFileBytes / sizeof(double); require(portable::read_u64(in, values) && values == expected_u64 && values <= maximum_values); result.coordinator.storage.regrets.resize(expected_values); for (auto& value : result.coordinator.storage.regrets) require(read_double(in, value)); require(portable::read_u64(in, values) && values == expected_u64); result.coordinator.storage.strategy_sums.resize(expected_values); for (auto& value : result.coordinator.storage.strategy_sums) require(read_double(in, value)); require(portable::read_u64(in, values) && values <= maximum_values); result.late_window_baseline.resize(static_cast<std::size_t>(values)); for (auto& value : result.late_window_baseline) require(read_double(in, value)); std::uint64_t stored_hash = 0U; require(portable::read_u64(in, stored_hash)); if (in.peek() != std::char_traits<char>::eof()) throw std::runtime_error("multiway training checkpoint has trailing data"); result.validate(); if (result.identity != expected_identity || result.training.schedule_hash != expected_schedule_hash || result.training.deterministic_seed != expected_seed || stored_hash != payload_hash(result)) throw std::invalid_argument("multiway training checkpoint identity or payload does not match"); return result;
}
}  // namespace texas::solver::multiway
